services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard_1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.eth0.proxy_ndp: 1
    environment:
      PUID: 1001
      PGID: 1001
      TZ: Europe/Paris
      SERVERURL: 192.168.1.2
      SERVERPORT: 51820
      PEERDNS: 1.1.1.1
      INTERNAL_SUBNET: fd00:abcd:f000::1
      ALLOWED_IPS: "::/0"
      LOG_CONFS: "true"
    networks:
      1_net:
        ipv4_address: 172.30.0.2
    ports:
      - 51820:51820/udp
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped

  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_1
    volumes:
       - .:/app
#      - ./scripts:/app/scripts
#      - ./playbooks:/app/playbooks
#      - ./reports:/app/reports
#      - ./inventory:/app/inventory
    environment:
      TZ: Europe/Paris
    networks:
      1_net:
        ipv4_address: 172.30.0.3
    restart: unless-stopped

networks:
  1_net:
    name: 1_net
    external: true
